# Generated by Django 4.2.8 on 2023-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog_featured_image')),
                ('slug', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
